const db = require("./connection");
const { User, PotentialMatch } = require("../models");
const { aggregate } = require("../models/PotentialMatch");
const { isNullableType, UniqueFieldDefinitionNamesRule } = require("graphql");
const { match_recompute } = require("../utils/make_matches.js");

db.once("open", async () => {
  await User.deleteMany();
  await PotentialMatch.deleteMany();

  await User.create({
    username: "Rosie Cotton",
    email: "rosie@theshire.net",
    password: "GreenDragon",
    matchmaker: false,
    profile_specified: true,
    gender: "female",
    age: 35,
    height: 38,
    weight: 90,
    eyes: "green",
    hair: "blonde",
    aboutMe:
      "I am sociable, patient, and love to dance. I am looking for someone who wants to make a home.",
    contactInfo: "rosie@theshire.net",
    wishlist_specified: true,
    wishgen_male: true,
    wishgen_female: false,
    wishgen_nonbinary: false,
    minage: 33,
    maxage: 100,
    minheight: 0,
    maxheight: 48,
    minweight: 0,
    maxweight: 1000,
    wisheye_brown: true,
    wisheye_blue: true,
    whisheye_gray: false,
    wisheye_green: true,
    wisheye_hazel: true,
    wishhair_black: true,
    wishhair_brown: true,
    wishhair_blond: true,
    wishhair_red: false,
    paid: true,
    match_found: false,
    found_match: null,
  });

  await User.create({
    username: "Julius Caesar",
    email: "jcaesar@empire.com",
    password: "IdesofMarch",
    matchmaker: false,
    profile_specified: true,
    gender: "male",
    age: 50,
    height: 68,
    weight: 170,
    eyes: "brown",
    hair: "brown",
    aboutMe:
      "My likes include Italian food, subjugating peoples, and receiving adoring crowds. Love to travel. Looking for someone who wants to be treated like a queen",
    contactInfo: "jcaesar@empire.com",
    wishlist_specified: true,
    wishgen_male: true,
    wishgen_female: true,
    wishgen_nonbinary: true,
    minage: 18,
    maxage: 35,
    minheight: 0,
    maxheight: 100,
    minweight: 0,
    maxweight: 1000,
    wisheye_brown: true,
    wisheye_blue: true,
    whisheye_gray: false,
    wisheye_green: true,
    wisheye_hazel: true,
    wishhair_black: true,
    wishhair_brown: true,
    wishhair_blond: false,
    wishhair_red: true,
    paid: true,
    match_found: false,
    found_match: null,
  });

  await User.create({
    username: "Sam Gamgee",
    email: "sgamgee@lotr.com",
    password: "Mellon",
    matchmaker: false,
    profile_specified: true,
    gender: "male",
    age: 39,
    height: 42,
    weight: 100,
    eyes: "green",
    hair: "blonde",
    aboutMe:
      "I am a homebody who loves gardening and home-cooked meals. I do not like traveling. Looking for someone who likes pipes and second breakfast",
    contactInfo: "sgamgee@lotr.com",
    wishlist_specified: true,
    wishgen_male: false,
    wishgen_female: true,
    wishgen_nonbinary: false,
    minage: 33,
    maxage: 100,
    minheight: 0,
    maxheight: 48,
    minweight: 0,
    maxweight: 1000,
    wisheye_brown: false,
    wisheye_blue: true,
    whisheye_gray: false,
    wisheye_green: true,
    wisheye_hazel: true,
    wishhair_black: true,
    wishhair_brown: true,
    wishhair_blond: true,
    wishhair_red: false,
    paid: true,
    match_found: false,
    found_match: null,
  });

  await User.create({
    username: "Hari Seldon",
    email: "hseldon@streeling.edu",
    password: "the Raven",
    matchmaker: false,
    profile_specified: true,
    gender: "male",
    age: 42,
    height: 70,
    weight: 180,
    eyes: "brown",
    hair: "brown",
    aboutMe:
      "I am a careful planner and not much for spontenaity. I am looking for someone who like peace and quiet but can take bad news with aplomb. Open to sentient AI. ",
    contactInfo: "hseldon@streeling.edu",
    wishlist_specified: true,
    wishgen_male: false,
    wishgen_female: true,
    wishgen_nonbinary: true,
    minage: 18,
    maxage: 100,
    minheight: 0,
    maxheight: 100,
    minweight: 0,
    maxweight: 1000,
    wisheye_brown: true,
    wisheye_blue: true,
    whisheye_gray: true,
    wisheye_green: true,
    wisheye_hazel: true,
    wishhair_black: true,
    wishhair_brown: true,
    wishhair_blond: true,
    wishhair_red: true,
    paid: true,
    match_found: false,
    found_match: null,
  });

  await User.create({
    username: "Cleopatra Philopator",
    email: "cphilopato@ptolemy.gov",
    password: "emerald",
    matchmaker: false,
    profile_specified: true,
    gender: "female",
    age: 27,
    height: 65,
    weight: 90,
    eyes: "blue",
    hair: "red",
    aboutMe:
      "I am sociable, patient, and love to dance. I am looking for someone who wants to make a home.",
    contactInfo: "'cphilopato@ptolemy.gov'",
    wishlist_specified: true,
    wishgen_male: true,
    wishgen_female: false,
    wishgen_nonbinary: false,
    minAge: 30,
    maxAge: 100,
    minHeight: 0,
    maxHeight: 100,
    minWeight: 0,
    maxWeight: 1000,
    wisheye_brown: true,
    wisheye_blue: true,
    whisheye_gray: false,
    wisheye_green: true,
    wisheye_hazel: true,
    wishhair_black: true,
    wishhair_brown: true,
    wishhair_blond: true,
    wishhair_red: false,
    paid: true,
    match_found: false,
    found_match: null,
  });

  await User.create({
    username: "Mark Antony",
    email: "mantony@secondtriumvirate.gov",
    password: "IamdyingEgyptdying.",
    matchmaker: false,
    profile_specified: true,
    gender: "male",
    age: 39,
    height: 68,
    weight: 170,
    eyes: "brown",
    hair: "brown",
    aboutMe: "I am a mamber of the College of Augurs",
    contactInfo: "mantony@secondtriumvirate.gov",
    wishlist_specified: true,
    wishgen_male: true,
    wishgen_female: true,
    wishgen_nonbinary: true,
    minAge: 18,
    maxAge: 35,
    minHeight: 0,
    maxHeight: 100,
    minWeight: 0,
    maxWeight: 1000,
    wisheye_brown: true,
    wisheye_blue: true,
    whisheye_gray: false,
    wisheye_green: false,
    wishhair_black: true,
    wishhair_brown: false,
    wishhair_blond: false,
    wishhair_red: true,
    paid: true,
    match_found: false,
    found_match: null,
  });

  await User.create({
    username: "Yenta",
    email: "Yenta@fiddlerontheroof.com",
    password: "12345678",
    matchmaker: true,
    profile_specified: false,
    wishlist_specified: false,
    paid: false,
    match_found: false,
  });

  console.log("users seeded");

  const matches_created = await match_recompute([]);
  console.log(String(matches_created) + " potential matches found.");

  process.exit(1);
});
