// export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";

// export const ADD_TO_CART = "ADD_TO_CART";
// export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
// export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
// export const CLEAR_CART = "CLEAR_CART";
// export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
// export const TOGGLE_CART = "TOGGLE_CART";

// export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
// export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";

export const FULL_USER = "FULL_USER";
export const ALL_MY_POTENTIAL_MATCHES = "ALL_MY_POTENTIAL_MATCHES";
export const UN_RATED_MATCHES = "UN_RATED_MATCHES";
export const MY_MATCH = "MY_MATCH";
export const RATE_A_MATCH = "RATE_A_MATCH";
export const CHOOSE_A_MATCH = "CHOOSE_A_MATCH";
export const REJECT_MATCH = "REJECT_MATCH";

